var data = [ 
    { "title": "Lili ne veut pas se coucher", "lu": "non" },
    { "title": "Max n aime pas lire", "lu": "non" },
    { "title": "Max est timide", "lu": "oui" },
    { "title": "Lili se dispute avec son frere", "lu": "non" },
    { "title": "Les parents de zoe divorcent", "lu": "non" },
    { "title": "Max n aime pas l ecole", "lu": "non" },
    { "title": "Lili est amoureuse", "lu": "non" },
    { "title": "Max fan de jeux video", "lu": "oui" },
    { "title": "Lili decouvre sa mamie", "lu": "non" },
    { "title": "Max va a l hopital", "lu": "non" },
    { "title": "Lili n aime que les frites", "lu": "oui" },
    { "title": "Max raconte des bobards", "lu": "oui" },
    { "title": "Max part en classe verte", "lu": "non" },
    { "title": "Lili est fachee avec sa copine", "lu": "oui" },
    { "title": "Max a triche", "lu": "oui" },
    { "title": "Lili a ete suivie", "lu": "oui" },
    { "title": "Max et lili ont peur", "lu": "oui" },
    { "title": "Max et lili ont vole des bonbons", "lu": "oui" },
    { "title": "Grand pere est mort", "lu": "non" },
    { "title": "Lili est desordre", "lu": "non" },
    { "title": "Max a la passion du foot", "lu": "oui" },
    { "title": "Lili veut choisir ses habits", "lu": "non" },
    { "title": "Lili veut proteger la nature", "lu": "oui" },
    { "title": "Max et koffi sont copains", "lu": "non" },
    { "title": "Lili veut un petit chat", "lu": "non" },
    { "title": "Les parents de max et lili se disputent", "lu": "non" },
    { "title": "Nina a ete adoptee", "lu": "non" },
    { "title": "Max est jaloux", "lu": "non" },
    { "title": "Max est maladroit", "lu": "oui" },
    { "title": "Lili veut de l argent de poche", "lu": "non" },
    { "title": "Max veut se faire des amis", "lu": "non" },
    { "title": "Emilie a demenage", "lu": "non" },
    { "title": "Lili ne veut plus aller a la piscine", "lu": "non" },
    { "title": "Max se bagarre", "lu": "oui" },
    { "title": "Max et lili se sont perdus", "lu": "oui" },
    { "title": "Jeremy est maltraite", "lu": "non" },
    { "title": "Lili se trouve moche", "lu": "non" },
    { "title": "Max est rackette", "lu": "oui" },
    { "title": "Max n aime pas perdre", "lu": "oui" },
    { "title": "Max a une amoureuse", "lu": "oui" },
    { "title": "Lili est malpolie", "lu": "oui" },
    { "title": "Max et lili veulent des calins", "lu": "non" },
    { "title": "Le pere de max et lili est au chomage", "lu": "non" },
    { "title": "Alex est handicape", "lu": "non" },
    { "title": "Max est casse cou", "lu": "non" },
    { "title": "Lili regarde trop la television", "lu": "oui" },
    { "title": "Max est dans la lune", "lu": "oui" },
    { "title": "Lili se fait toujours gronder", "lu": "non" },
    { "title": "Max adore jouer", "lu": "non" },
    { "title": "Max et lili veulent tout savoir sur les bebe", "lu": "oui" },
    { "title": "Lucien n a pas de copains", "lu": "non" },
    { "title": "Lili a peur des controles", "lu": "non" },
    { "title": "Max et lili veulent tout tout de suite", "lu": "oui" },
    { "title": "Max embete les filles", "lu": "non" },
    { "title": "Lili va chez la psy", "lu": "non" },
    { "title": "Max ne veut pas se laver", "lu": "non" },
    { "title": "Lili trouve sa maitresse mechante", "lu": "non" },
    { "title": "Max et lili sont malades", "lu": "non" },
    { "title": "Max fait pipi au lit", "lu": "oui" },
    { "title": "Lili fait des cauchemars", "lu": "non" },
    { "title": "Le cousin de max et lili se drogue", "lu": "non" },
    { "title": "Max et lili ne font pas leurs devoirs", "lu": "non" },
    { "title": "Max va a la peche avec son pere", "lu": "non" },
    { "title": "Marlene grignote tout le temps", "lu": "non" },
    { "title": "Lili veut etre une star", "lu": "non" },
    { "title": "La copine de lili a une maladie grave", "lu": "non" },
    { "title": "Max se fait insulter a la recre", "lu": "non" },
    { "title": "La maison de max et lili a ete cambriolee", "lu": "non" },
    { "title": "Lili veut faire une boum", "lu": "non" },
    { "title": "Max n en fait qu a sa tete", "lu": "non" },
    { "title": "Le chien de max et lili est mort", "lu": "oui" },
    { "title": "Simon a deux maisons", "lu": "oui" },
    { "title": "Max veut etre delegue de classe", "lu": "non" },
    { "title": "Max et lili aident les enfants du monde", "lu": "non" },
    { "title": "Lili se fait pieger sur internet", "lu": "oui" },
    { "title": "Emilie n aime pas quand sa mere boit trop", "lu": "non" },
    { "title": "Max ne respecte rien", "lu": "non" },
    { "title": "Max aime les monstres", "lu": "non" },
    { "title": "Lili ne veut plus se montrer toute nue", "lu": "non" },
    { "title": "Lili part en camp de vacances", "lu": "non" },
    { "title": "Max se trouve nul", "lu": "oui" },
    { "title": "Max et lili fetent noel en famille", "lu": "non" },
    { "title": "Lili a un chagrin d amour", "lu": "non" },
    { "title": "Max trouve que c est pas juste", "lu": "non" },
    { "title": "Max et lili sont fans de marques", "lu": "non" },
    { "title": "Max et lili se posent des questions sur dieu", "lu": "non" },
    { "title": "Max ne pense qu au zizi", "lu": "oui" },
    { "title": "Lili fait sa commandante", "lu": "oui" },
    { "title": "Max decide de faire des efforts", "lu": "non" },
    { "title": "Lili a peur de la mort", "lu": "non" },
    { "title": "Lili reve d etre une femme", "lu": "non" },
    { "title": "Lili a la passion du cheval", "lu": "oui" },
    { "title": "Max et lili veulent eduquer leurs parents", "lu": "non" },
    { "title": "Lili veut un telephone portable", "lu": "non" },
    { "title": "Le tonton de max et lili est en prison", "lu": "oui" },
    { "title": "Max veut sauver les animaux", "lu": "non" },
    { "title": "Lili est stressee par la rentree", "lu": "non" },
    { "title": "Max et lili veulent etre gentils", "lu": "non" },
    { "title": "Lili est harcelee a l ecole", "lu": "oui" },
    { "title": "Max et lili ont des pouvoirs magiques", "lu": "oui" },
    { "title": "Max boude", "lu": "non" },
    { "title": "Max et lili font du camping", "lu": "non" },
    { "title": "Max et lili en ont marre de se depecher", "lu": "non" },
    { "title": "Lili a trop honte", "lu": "non" },
    { "title": "Lili invite une copine en vacances", "lu": "non" },
    { "title": "Max et lili veulent etre populaires", "lu": "non" },
    { "title": "Max et lili trouvent leur cousin angoisse", "lu": "non" },
    { "title": "Max et lili vont chez papy et mamie", "lu": "non" },
    { "title": "Max et lili ont peur des images violentes", "lu": "non" },
    { "title": "La copine de lili n a pas de papa", "lu": "non" },
    { "title": "Max se trouve trop petit", "lu": "oui" },
    { "title": "Max et lili cherchent leur metier", "lu": "non" },
    { "title": "Max en a marre de sa soeur", "lu": "oui" },
    { "title": "Max et lili decident de mieux manger", "lu": "non" },
    { "title": "Max et lili ont du mal a se concentrer", "lu": "non" },
    { "title": "La copine de lili est en famille d accueil", "lu": "non" },
    { "title": "Max et lili n osent pas parler en public", "lu": "non" },
    { "title": "Max et lili veulent rester en vacances", "lu": "non" },
    { "title": "Max et lili disent que c est pas de leur faut", "lu": "non" },
    { "title": "Lili veut jouer au foot", "lu": "oui" },
    { "title": "Les parents de max et lili sont accros au portable", "lu": "oui" },
    { "title": "Max et lili ont peur du noir", "lu": "non" },
    { "title": "Max se sent seul", "lu": "oui" },
    { "title": "Max et lili veulent soigner tout le monde", "lu": "non" },
    { "title": "Max et lili aiment trop rire", "lu": "non" },
    { "title": "Max et lili veulent se debrouiller seuls", "lu": "oui" },
    { "title": "Max croit n importe quoi", "lu": "non" },
    { "title": "Max et lili font les baby sitters", "lu": "non" }
    ];

    data.forEach((item, index) => {
        var row = dataTable.insertRow();
        row.insertCell(0).innerHTML = index+1;
        row.insertCell(1).innerHTML = item.title;
        row.insertCell(2).innerHTML = item.lu;
        if (item.lu === "oui") row.className = "lu";
      });